- name: "install prometheus"
  become: yes
  remote_user: "{{ ssh_remote_user }}"
  community.general.pacman:
    name: prometheus
    state: present

- name: "install prometheus-node-exporter"
  become: yes
  remote_user: "{{ ssh_remote_user }}"
  community.general.pacman:
    name: prometheus-node-exporter
    state: present

- name: "enable prometheus service"
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started
  become: yes

- name: "enable prometheus-node-exporter service"
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: yes
    state: started
  become: yes
